name: Deploy to VPS

# Esto le dice a GitHub que ejecute este flujo cada vez que hagas 'push' a la rama 'main'
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest # El tipo de m치quina virtual que usar치 GitHub

    steps:
    - name: 游뚴 Deploy to VPS via SSH
      uses: appleboy/ssh-action@master # Usamos una acci칩n pre-hecha para facilitar el SSH
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Navega a la carpeta de tu proyecto en el VPS
          cd /opt/BOT
          
          # Descarga el c칩digo m치s reciente desde GitHub
          git pull
          
          # Reconstruye la imagen de Docker
          docker build -t whatsapp-bot .
          
          # Detiene y elimina el contenedor antiguo si existe
          docker stop bot-wa || true
          docker rm bot-wa || true
          
          # Ejecuta el nuevo contenedor
          docker run -d --restart always --name bot-wa -p 3000:3000 -v /opt/BOT/sesiones.db:/usr/src/app/sesiones.db whatsapp-bot